### ISSUE TITLE
No sourcemapping

### ISSUE THREAD

**Issue by eddyerburgh** [vire/jest-vue-preprocessor#32] opened 2017-08-12 06:53 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
There are no sourcemaps

**Expected behavior**
Sourcemaps should be generated using similar logic to vueify

**What is the motivation / use case for changing the behavior?**
Code coverage report is incorrect, I would like to use this preprocessor in the webpack vue-cli template, but we can't use it until correct source maps are generated.

* **jest-vue-preprocessor:** 1.X

**Comment by vire** [comment] 2017-08-13 18:16
hey @eddyerburgh,

I think you need to elaborate a bit more on this so we can come to an conclusion if this is generating sourcemaps is an concern of `jest-vue-preprocessor`.

In case you need sourcemaps for babel (which i think should help with coverage for javascript code), then just add `"sourceMaps": "inline" ` to .babelrc.

But if you need sourcemaps for the whole file, that's more complicated since under the hood, the component is parsed with `vue-template-compiler` and `vue-template-es2015-compiler` so I'd have to join `<script>` and `<template>` source maps here...

**Comment by vire** [comment] 2017-08-13 18:22
This is a duplicate of #15

**Closed** 2017-08-13 18:27 UTC
Labels: enhancement

**Comment by eddyerburgh** [comment] 2017-08-13 20:09
Hi @vire . Sorry if I wasn't clear.

I would like sourcemaps for .vue files.

Generating source maps for .vue files needs to be done in jest vue preprocessor. You can return an object containing the  javascript and a sourcemap from the process function.

It is quite complicated, but it's possible. The logic exists in vueify
